import type { Metadata } from "next";
import { Irish_Grover } from "next/font/google";
// import { css } from "../../styled-system/css";
import "./globals.css";

const irishGrover = Irish_Grover({
  weight: ["400"],
  display: "swap",
  subsets: ["latin"],
  variable: "--font-irish-grover",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${irishGrover.variable}`} lang="en">
      <body>
        {/* <body className={css({ background: "light.surface.page" })}> */}
        {children}
      </body>
    </html>
  );
}
